server:
  port: 8081
spring:
  application:
    name: my-app
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
app:
  name: my-app
  version: "1.0"
  description: "This is learning app"
jwt:
  secret: my-super-secret-key-for-jwt-must-be-at-least-256-bits-long-for-hs256
  access-token-expiration: 900000    # 15 phút (milliseconds)
  refresh-token-expiration: 604800000 # 7 ngày (milliseconds)
